### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by AllThingsSmitty** [laramap/laramap.com#1]
An ideal browser support model would include the latest version of major browsers, and a specific segment of IE. E.g.:

* Chrome *(latest 2)*
* Edge *(latest 2)*
* Firefox *(latest 2)*
* Internet Explorer 8+
* Opera *(latest 2)*
* Safari *(latest 2)*

And integrating a feature like Autoprefixer would also help.

**Comment by fwartner** [comment]
Create a PR and i will merge it :)

**Comment by AllThingsSmitty** [comment]
👍🏼
