### ISSUE TITLE
LinkedIn-Profile's placeholder

### ISSUE THREAD

**Issue by hatamiarash7** [laramap/laramap.com#2]
**Describe the bug**
The placeholder text for `LinkedIn-Profile` is wrong.

**To Reproduce**
1. Go to 'Account` page

**Expected behavior**
The correct link for LinkedIn pages is : `https://linkedin.com/in/fwartner` but there is a wrong link as follow : `https://linkedin.com/fwartner`

**Comment by fwartner** [comment]
Would you mind to create a PR for it? :)

**Comment by hatamiarash7** [comment]
Ok, Sure ... :) @fwartner
