### ISSUE TITLE
Broken 'Your profile looks so empty' email 

### ISSUE THREAD

**Issue by snapey** [laramap/laramap.com#26]
**Describe the bug**
I get an email asking me to update my profile. When I click on the link I get page not found.  Page is laramap.com/settings

I login. Clicking on profile only shows a card with my avatar and name. No option to set any profile

**To Reproduce**
* Click on the link in the email

**Expected behavior**
expect to be able to update profile.

**Comment by fwartner** [comment]
Hey @snapey ! Thanks for the report!

Will be fixed in the next release. :)
