### ISSUE TITLE
Composer update error

### ISSUE THREAD

**Issue by vjandrea** [laramap/laramap.com#5]
After running composer update:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - remove alfredo-ramos/parsedown-extra-laravel 0.3.x-dev|keep alfredo-ramos/parsedown-extra-laravel dev-master
    - alfredo-ramos/parsedown-extra-laravel 0.3.0 requires mews/purifier ~2.0 -> no matching package found.
    - alfredo-ramos/parsedown-extra-laravel dev-master requires mews/purifier ~2.0 -> no matching package found.
    - Installation request for alfredo-ramos/parsedown-extra-laravel ^0.3.0@dev -> satisfiable by alfredo-ramos/parsedow
n-extra-laravel[0.3.0, 0.3.x-dev].

Any suggestion?

**Comment by fwartner** [comment]
Fixed now.

**Comment by vjandrea** [comment]
Tried with homestead to create a reproducible environment, same problem.

vagrant@homestead:~/Code$ composer update
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - remove alfredo-ramos/parsedown-extra-laravel 0.3.x-dev|keep alfredo-ramos/parsedown-extra-laravel dev-master
    - alfredo-ramos/parsedown-extra-laravel 0.3.0 requires mews/purifier ~2.0 -> no matching package found.
    - alfredo-ramos/parsedown-extra-laravel dev-master requires mews/purifier ~2.0 -> no matching package found.
    - Installation request for alfredo-ramos/parsedown-extra-laravel ^0.3.0@dev -> satisfiable by alfredo-ramos/parsedown-extra-laravel[0.3.0, 0.3.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
vagrant@homestead:~/Code$
