### ISSUE TITLE
Contribution instructions missing, many errors

### ISSUE THREAD

**Issue by vjandrea** [laramap/laramap.com#6]
I'm trying to have the project running in Homestead but there are many problems, i.e.:
- `composer install` fails because APP_KEY hasn't the proper lenght. `artisan key:generate` fails as well for the same reason, it may be solved writing a 32char string as APP_KEY and then running `key:generate`
- `storage` folder missing: it's normally present in laravel/laravel. This causes issues with views cache.
- ROLLBAR_TOKEN missing. Solved creating a free account
- ALGOLIA_TOKEN missing. May be solved creating a free account. 
- tests missing
- *FatalThrowableError in MemcachedConnector.php line 51: Fatal error: Class 'Memcached' not found*, while memcache and memcached are both installed.
I wonder what else is required to make it run correctly.

Would it be possible to have a reproducible setup in order to make it a bit easier to contribute?

**Comment by fwartner** [comment]
To fix the Memcached issue, you can simply choose an other cache provider in you .env file..
Should solve the problem.

**Comment by fwartner** [comment]
Feel free to add a guideline or whatever you want to add.. :)

**Comment by SilverPaladin** [comment]
1: set ROLLBAR_TOKEN= (go to rollbar.com and sign up for token) in .env
2: create storage folder, I copied the structure from another project
3: set up database stuff and add connection info to .env
4: create app key 

now I can run composer install without error

**Comment by vjandrea** [comment]
@SilverPaladin i started a contributing.md doc, so please feel free to contribute! https://github.com/laramap/laramap.com/blob/master/CONTRIBUTING.md
Right now i have issues with vendor views, still trying to debug that.

**Comment by fwartner** [comment]
Thanks to @vjandrea ! It´s online again but there are some problems with the map and the profiles using parsedown.. :cry:

**Comment by vjandrea** [comment]
Looks like now we have to deal with JS errors: in my browser's console i can see:
````
TypeError: $(...).modal is not a function
<anonymous> laramap.com:139
1 laramap.com:139:9
````
and
````
TypeError: $(...).feedback is not a function
<anonymous> app-2edc2510e2.js:56
n.Callbacks/j() jquery.min.js:2
n.Callbacks/k.fireWith() jquery.min.js:2
.ready() jquery.min.js:2
K() jquery.min.js:2
1 app-2edc2510e2.js:56:5
````
