### ISSUE TITLE
Site down!!

### ISSUE THREAD

**Issue by mohanmoorthy** [laramap/laramap.com#8]
Seems something went wrong.

**Comment by fwartner** [comment]
Clone the repo, install it locally using homestead and try to get it working.. After that, i´m happy if you would create a PR to merge and deploy.. :)

**Comment by vjandrea** [comment]
@fwartner what's the error you see in logs? There are so many external services involved that i'm still struggling to get my fork operative.

**Comment by fwartner** [comment]
While trying to exclude the services, i´m getting something about the view composer.. Something´s seems to be wrong with it.. Which is really strange because it wasn’t present until i did a composer update..

**Comment by vjandrea** [comment]
@fwartner on my local fork i can see this error:

ErrorException in FileViewFinder.php line 112: No hint path defined for [parsedownextra]. (View: <snip>/laramap.com/resources/views/includes/default/footer.blade.php) (View: <snip>/laramap.com/resources/views/includes/default/footer.blade.php) (View: <snip>/laramap.com/resources/views/includes/default/footer.blade.php)

**Comment by vjandrea** [comment]
I think i've found the issue in some views, but i don't know if my solution is the cleanest way to fix it.
In `layouts/default.blade.php` and in `includes/default/header.blade.php` and `footer.blade.php` i changed `@include('parsedonwextra::` to `@include('vendor.parsedownextra.`, now the subviews are included correctly and i can render the pages without errors.

**Comment by vjandrea** [comment]
@fwartner I found some commented elements, with the PR #11 locally it works again

**Comment by dikiaap** [comment]
Larmap down again?

**Comment by fwartner** [comment]
Yeah... Because of caching issues.. Will fix this tomorrow. 

Von meinem iPhone gesendet

**Comment by insign** [comment]
Down again?
